# Generated by Django 5.2 on 2025-04-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerevaCoords',
            new_name='PerevalCoords',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='PerevalUser',
        ),
    ]
